
import type { Exercise } from '@/lib/schemas';

export const sampleExercises: Exercise[] = [
  {
    id: 'push-up',
    name: 'Push Up',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    instructions: [
      'Get down on all fours, placing your hands slightly wider than your shoulders.',
      'Straighten your arms and legs.',
      'Lower your body until your chest nearly touches the floor.',
      'Push yourself back up.',
    ],
    imageUrl: 'https://picsum.photos/seed/pushup/600/400',
    imageHint: 'push up',
  },
  {
    id: 'squat',
    name: 'Squat',
    muscleGroup: 'Legs',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    instructions: [
      'Stand with your feet slightly wider than your hips.',
      'Lower your hips back and down as if sitting in a chair.',
      'Keep your chest up and your back straight.',
      'Push through your heels to return to the starting position.',
    ],
    imageUrl: 'https://picsum.photos/seed/squat/600/400',
    imageHint: 'squat exercise',
  },
  {
    id: 'plank',
    name: 'Plank',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    instructions: [
      'Place your forearms on the floor with your elbows aligned below your shoulders.',
      'Your arms should be parallel to your body, about shoulder-width apart.',
      'Hold your body in a straight line from head to heels.',
      'Engage your core and hold the position.',
    ],
    imageUrl: 'https://picsum.photos/seed/plank/600/400',
    imageHint: 'plank exercise',
  },
  {
    id: 'dumbbell-bicep-curl',
    name: 'Dumbbell Bicep Curl',
    muscleGroup: 'Arms',
    equipment: 'Dumbbells',
    difficulty: 'Beginner',
    instructions: [
      'Stand or sit holding a dumbbell in each hand with an underhand grip.',
      'Curl the weights up towards your shoulders, keeping your elbows stationary.',
      'Squeeze your biceps at the top of the movement.',
      'Slowly lower the weights back to the starting position.',
    ],
    imageUrl: 'https://picsum.photos/seed/bicepcurl/600/400',
    imageHint: 'bicep curl',
  },
  {
    id: 'pull-up',
    name: 'Pull Up',
    muscleGroup: 'Back',
    equipment: 'Pull-up Bar',
    difficulty: 'Advanced',
    instructions: [
        'Grab the pull-up bar with your palms facing away from you.',
        'Hang with your arms fully extended.',
        'Pull your body up until your chin is above the bar.',
        'Lower your body back down to the starting position in a controlled manner.',
    ],
    imageUrl: 'https://picsum.photos/seed/pullup/600/400',
    imageHint: 'pull up',
  },
   {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    muscleGroup: 'Legs',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    instructions: [
        'Lie on your back with your knees bent and feet flat on the floor.',
        'Place your arms at your sides with your palms down.',
        'Lift your hips off the floor until your knees, hips and shoulders form a straight line.',
        'Squeeze your glutes and keep your abs drawn in so you don’t overextend your back.',
        'Hold for a few seconds before easing back down.',
    ],
    imageUrl: 'https://picsum.photos/seed/glutebridge/600/400',
    imageHint: 'glute bridge',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    muscleGroup: 'Back',
    equipment: 'Dumbbells',
    difficulty: 'Intermediate',
    instructions: [
        'Place one knee and hand on a bench, holding a dumbbell in the other hand.',
        'Keep your back flat and parallel to the ground.',
        'Pull the dumbbell up towards your chest, keeping your elbow close to your body.',
        'Squeeze your back muscles at the top.',
        'Lower the dumbbell slowly to the starting position.',
    ],
    imageUrl: 'https://picsum.photos/seed/dumbbellrow/600/400',
    imageHint: 'dumbbell row',
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    muscleGroup: 'Full Body',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    instructions: [
        'Stand with your feet together and your arms at your sides.',
        'Simultaneously jump your feet out to the sides while raising your arms above your head.',
        'Jump back to the starting position.',
        'Repeat for the desired number of repetitions or time.',
    ],
    imageUrl: 'https://picsum.photos/seed/jumpingjacks/600/400',
    imageHint: 'jumping jacks',
  },
];
